In [3]:
import os
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import koreanize_matplotlib

In [8]:
# 파일 목록 불러오기
data = os.listdir(r'C:\bigdata\data\전국부동산실거래가')
data = data[:-8]
data

['1999_01.csv',
 '1999_02.csv',
 '1999_03.csv',
 '1999_04.csv',
 '1999_05.csv',
 '1999_06.csv',
 '1999_07.csv',
 '1999_08.csv',
 '1999_09.csv',
 '1999_10.csv',
 '1999_11.csv',
 '1999_12.csv',
 '2000_01.csv',
 '2000_02.csv',
 '2000_03.csv',
 '2000_04.csv',
 '2000_05.csv',
 '2000_06.csv',
 '2000_07.csv',
 '2000_08.csv',
 '2000_09.csv',
 '2000_10.csv',
 '2000_11.csv',
 '2000_12.csv',
 '2001_01.csv',
 '2001_02.csv',
 '2001_03.csv',
 '2001_04.csv',
 '2001_05.csv',
 '2001_06.csv',
 '2001_07.csv',
 '2001_08.csv',
 '2001_09.csv',
 '2001_10.csv',
 '2001_11.csv',
 '2001_12.csv',
 '2002_01.csv',
 '2002_02.csv',
 '2002_03.csv',
 '2002_04.csv',
 '2002_05.csv',
 '2002_06.csv',
 '2002_07.csv',
 '2002_08.csv',
 '2002_09.csv',
 '2002_10.csv',
 '2002_11.csv',
 '2002_12.csv',
 '2003_01.csv',
 '2003_02.csv',
 '2003_03.csv',
 '2003_04.csv',
 '2003_05.csv',
 '2003_06.csv',
 '2003_07.csv',
 '2003_08.csv',
 '2003_09.csv',
 '2003_10.csv',
 '2003_11.csv',
 '2003_12.csv',
 '2004_01.csv',
 '2004_02.csv',
 '2004_03.csv',
 '2004_04.csv',
 '2004_05.csv',
 '2004_06.csv',
 '2004_07.csv',
 '2004_08.csv',
 '2004_09.csv',
 '2004_10.csv',
 '2004_11.csv',
 '2004_12.csv',
 '2005_01.csv',
 '2005_02.csv',
 '2005_03.csv',
 '2005_04.csv',
 '2005_05.csv',
 '2005_06.csv',
 '2005_07.csv',
 '2005_08.csv',
 '2005_09.csv',
 '2005_10.csv',
 '2005_11.csv',
 '2005_12.csv',
 '2006_01.csv',
 '2006_02.csv',
 '2006_03.csv',
 '2006_04.csv',
 '2006_05.csv',
 '2006_06.csv',
 '2006_07.csv',
 '2006_08.csv',
 '2006_09.csv',
 '2006_10.csv',
 '2006_11.csv',
 '2006_12.csv',
 '2007_01.csv',
 '2007_02.csv',
 '2007_03.csv',
 '2007_04.csv',
 '2007_05.csv',
 '2007_06.csv',
 '2007_07.csv',
 '2007_08.csv',
 '2007_09.csv',
 '2007_10.csv',
 '2007_11.csv',
 '2007_12.csv',
 '2008_01.csv',
 '2008_02.csv',
 '2008_03.csv',
 '2008_04.csv',
 '2008_05.csv',
 '2008_06.csv',
 '2008_07.csv',
 '2008_08.csv',
 '2008_09.csv',
 '2008_10.csv',
 '2008_11.csv',
 '2008_12.csv',
 '2009_01.csv',
 '2009_02.csv',
 '2009_03.csv',
 '2009_04.csv',
 '2009_05.csv',
 '2009_06.csv',
 '2009_07.csv',
 '2009_08.csv',
 '2009_09.csv',
 '2009_10.csv',
 '2009_11.csv',
 '2009_12.csv',
 '2010_01.csv',
 '2010_02.csv',
 '2010_03.csv',
 '2010_04.csv',
 '2010_05.csv',
 '2010_06.csv',
 '2010_07.csv',
 '2010_08.csv',
 '2010_09.csv',
 '2010_10.csv',
 '2010_11.csv',
 '2010_12.csv',
 '2011_01.csv',
 '2011_02.csv',
 '2011_03.csv',
 '2011_04.csv',
 '2011_05.csv',
 '2011_06.csv',
 '2011_07.csv',
 '2011_08.csv',
 '2011_09.csv',
 '2011_10.csv',
 '2011_11.csv',
 '2011_12.csv',
 '2012_01.csv',
 '2012_02.csv',
 '2012_03.csv',
 '2012_04.csv',
 '2012_05.csv',
 '2012_06.csv',
 '2012_07.csv',
 '2012_08.csv',
 '2012_09.csv',
 '2012_10.csv',
 '2012_11.csv',
 '2012_12.csv',
 '2013_01.csv',
 '2013_02.csv',
 '2013_03.csv',
 '2013_04.csv',
 '2014_01.csv',
 '2014_02.csv',
 '2014_03.csv',
 '2014_04.csv',
 '2014_05.csv',
 '2014_06.csv',
 '2014_07.csv',
 '2014_08.csv',
 '2014_09.csv',
 '2014_10.csv',
 '2014_11.csv',
 '2014_12.csv',
 '2015_01.csv',
 '2015_02.csv',
 '2015_03.csv',
 '2015_04.csv',
 '2015_05.csv',
 '2015_06.csv',
 '2015_07.csv',
 '2015_08.csv',
 '2015_09.csv',
 '2015_10.csv',
 '2015_11.csv',
 '2015_12.csv',
 '2016_01.csv',
 '2016_02.csv',
 '2016_03.csv',
 '2016_04.csv',
 '2016_05.csv',
 '2016_06.csv',
 '2016_07.csv',
 '2016_08.csv',
 '2016_09.csv',
 '2016_10.csv',
 '2016_11.csv',
 '2016_12.csv',
 '2017_01.csv',
 '2017_02.csv',
 '2017_03.csv',
 '2017_04.csv',
 '2017_05.csv',
 '2017_06.csv',
 '2017_07.csv',
 '2017_08.csv',
 '2017_09.csv',
 '2017_10.csv',
 '2017_11.csv',
 '2017_12.csv',
 '2018_01.csv',
 '2018_02.csv',
 '2018_03.csv',
 '2018_04.csv',
 '2018_05.csv',
 '2018_06.csv',
 '2018_07.csv',
 '2018_08.csv',
 '2018_09.csv',
 '2018_10.csv',
 '2018_11.csv',
 '2018_12.csv',
 '2019_01.csv',
 '2019_02.csv',
 '2019_03.csv',
 '2019_04.csv',
 '2019_05.csv',
 '2019_06.csv',
 '2019_07.csv',
 '2019_08.csv',
 '2019_09.csv',
 '2019_10.csv',
 '2019_11.csv',
 '2019_12.csv',
 '2020_01.csv',
 '2020_02.csv',
 '2020_03.csv',
 '2020_04.csv',
 '2020_05.csv',
 '2020_06.csv',
 '2020_07.csv',
 '2020_08.csv',
 '2020_09.csv',
 '2020_10.csv',
 '2020_11.csv',
 '2020_12.csv',
 '2021_01.csv',
 '2021_02.csv',
 '2021_03.csv',
 '2021_04.csv',
 '2021_05.csv',
 '2021_06.csv',
 '2021_07.csv',
 '2021_08.csv',
 '2021_09.csv',
 '2021_10.csv',
 '2021_11.csv',
 '2021_12.csv',
 '2022_01.csv',
 '2022_02.csv',
 '2022_03.csv',
 '2022_04.csv',
 '2022_05.csv',
 '2022_06.csv',
 '2022_07.csv',
 '2022_08.csv',
 '2022_09.csv',
 '2022_10.csv',
 '2022_11.csv',
 '2022_12.csv',
 '2023_01.csv',
 '2023_02.csv',
 '2023_03.csv',
 '2023_04.csv',
 '2023_05.csv',
 '2023_06.csv',
 '2023_07.csv',
 '2023_08.csv']

In [11]:
df = pd.read_csv(r"C:\bigdata\data\전국부동산실거래가\2005_10.csv",encoding="cp949",skiprows=15)

In [12]:
df

,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명,해제사유발생일,등기신청일자,거래유형,중개사소재지
0,경기도 의정부시 민락동,756-7,756,7,한라비발디,84.990,200510,30,"12,750",19,2003,오목로 73,NaN,,-,-
1,경기도 의정부시 신곡동,456,456,0,신일1,59.878,200510,20,"5,750",3,1997,시민로245번길 10,NaN,,-,-
2,경기도 의정부시 신곡동,727-1,727,1,풍림,49.830,200510,20,"5,500",8,1998,회룡로 245,NaN,,-,-

In [13]:
hap = pd.DataFrame()
for i in data:
    data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
    merged_data = pd.concat([hap,data1])

C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)

C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)
C:\Users\hi\AppData\Local\Temp\ipykernel_8376\159086775.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(f"C:/bigdata/data/전국부동산실거래가/{i}",encoding="cp949",skiprows=15)

In [14]:
merged_data.head()

,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명,해제사유발생일,등기신청일자,거래유형,중개사소재지
0,강원특별자치도 강릉시 견소동,202,0202,0,송정한신,59.800,202308,8,"23,000",9,1997.0,경강로2539번길 8,NaN,,중개거래,강릉시
1,강원특별자치도 강릉시 견소동,202,0202,0,송정한신,84.945,202308,14,"31,000",13,1997.0,경강로2539번길 8,NaN,,중개거래,강릉시
2,강원특별자치도 강릉시 견소동,202,0202,0,송정한신,43.380,202308,30,"16,400",10,1997.0,경강로2539번길 8,NaN,,중개거래,강릉시
3,강원특별자치도 강릉시 견소동,289,0289,0,송정해변신도브래뉴아파트,59.990,202308,19,"24,500",5,2005.0,경강로2539번길 23,NaN,,중개거래,강릉시
4,강원특별자치도 강릉시 견소동,289,0289,0,송정해변신도브래뉴아파트,84.990,202308,22,"28,500",4,2005.0,경강로2539번길 22,NaN,,중개거래,강릉시

In [15]:
merged_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30916 entries, 0 to 30915
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   시군구       30916 non-null  object
 1   번지        30915 non-null  object
 2   본번        30916 non-null  object
 3   부번        30916 non-null  int64
 4   단지명       30916 non-null  object
 5   전용면적(㎡)   30916 non-null  float64
 6   계약년월      30916 non-null  int64
 7   계약일       30916 non-null  int64
 8   거래금액(만원)  30916 non-null  object
 9   층         30916 non-null  int64
 10  건축년도      30903 non-null  float64
 11  도로명       30916 non-null  object
 12  해제사유발생일   602 non-null    float64
 13  등기신청일자    30916 non-null  object
 14  거래유형      30916 non-null  object
 15  중개사소재지    30916 non-null  object
dtypes: float64(3), int64(4), object(9)
memory usage: 3.8+ MB

In [19]:
data = merged_data.drop(['번지','본번','부번','단지명','계약일','도로명','해제사유발생일','등기신청일자','거래유형','중개사소재지'],axis=1)

In [22]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30916 entries, 0 to 30915
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   시군구       30916 non-null  object
 1   전용면적(㎡)   30916 non-null  float64
 2   계약년월      30916 non-null  int64
 3   거래금액(만원)  30916 non-null  object
 4   층         30916 non-null  int64
 5   건축년도      30903 non-null  float64
dtypes: float64(2), int64(2), object(2)
memory usage: 1.4+ MB

In [25]:
data['거래금액(만원)'] = data['거래금액(만원)'].str.replace(",","")

In [28]:
data['거래금액(만원)'] = data['거래금액(만원)'].astype(int)

In [29]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30916 entries, 0 to 30915
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   시군구       30916 non-null  object
 1   전용면적(㎡)   30916 non-null  float64
 2   계약년월      30916 non-null  int64
 3   거래금액(만원)  30916 non-null  int32
 4   층         30916 non-null  int64
 5   건축년도      30903 non-null  float64
dtypes: float64(2), int32(1), int64(2), object(1)
memory usage: 1.3+ MB

In [31]:
data[data['건축년도'].isna()]

                   시군구   전용면적(㎡)    계약년월  거래금액(만원)   층  건축년도
537    강원특별자치도 원주시 무실동   59.9678  202308     34500  23   NaN
538    강원특별자치도 원주시 무실동   84.9836  202308     49700  13   NaN
539    강원특별자치도 원주시 무실동   84.9836  202308     45800  19   NaN
540    강원특별자치도 원주시 무실동   59.9230  202308     36000  24   NaN
541    강원특별자치도 원주시 무실동   84.9768  202308     48950  27   NaN
542    강원특별자치도 원주시 무실동   84.9768  202308     50500  15   NaN
9031       경기도 화성시 오산동   71.6544  202308     95000   3   NaN
26438     전라북도 군산시 조촌동   84.9959  202308     39400   7   NaN
26439     전라북도 군산시 조촌동  103.9793  202308     55800  12   NaN
26440     전라북도 군산시 조촌동   84.9959  202308     42000  13   NaN
26441     전라북도 군산시 조촌동   84.9959  202308     39700   9   NaN
26442     전라북도 군산시 조촌동   84.9959  202308     36700   3   NaN
26443     전라북도 군산시 조촌동   84.9983  202308     42000  24   NaN

In [33]:
data = data.dropna()

In [34]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30903 entries, 0 to 30915
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   시군구       30903 non-null  object
 1   전용면적(㎡)   30903 non-null  float64
 2   계약년월      30903 non-null  int64
 3   거래금액(만원)  30903 non-null  int32
 4   층         30903 non-null  int64
 5   건축년도      30903 non-null  float64
dtypes: float64(2), int32(1), int64(2), object(1)
memory usage: 1.5+ MB

In [36]:
data['건축년도'] = data['건축년도'].astype(int)

In [37]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30903 entries, 0 to 30915
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   시군구       30903 non-null  object
 1   전용면적(㎡)   30903 non-null  float64
 2   계약년월      30903 non-null  int64
 3   거래금액(만원)  30903 non-null  int32
 4   층         30903 non-null  int64
 5   건축년도      30903 non-null  int32
dtypes: float64(1), int32(2), int64(2), object(1)
memory usage: 1.4+ MB

In [38]:
from sklearn.preprocessing import LabelEncoder

In [40]:
le = LabelEncoder()
data['시군구'] = le.fit_transform(data['시군구'])
print(le.classes_)

['강원특별자치도 강릉시 견소동' '강원특별자치도 강릉시 교동' '강원특별자치도 강릉시 남문동' ... '충청북도 충주시 칠금동'
 '충청북도 충주시 풍동' '충청북도 충주시 호암동']